<!DOCTYPE html>

<html class="no-js" dir="ltr" lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <meta content="La Boutique HTML v3.0" name="author">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Home | La Boutique</title>
    <link href="css/bootstrap.css" rel="stylesheet" type="text/css">
    <link href="css/bootstrap-responsive.css" rel="stylesheet" type="text/css">
    <link href="css/fonts/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="css/flexslider.css" rel="stylesheet" type="text/css">
    <!-- Comment following two lines to use LESS -->
    <link href="css/color-schemes/core.css" rel="stylesheet" type="text/css">
    <link href="css/color-schemes/turquoise.css" id="color_scheme" rel=
    "stylesheet" type="text/css">
    <!-- Uncomment following three lines to use LESS -->
    <!--<link rel="stylesheet/less" type="text/css" href="css/less/core.less">
<link rel="stylesheet/less" type="text/css" href="css/less/turquoise.less" id="color_scheme" >
<script src="js/less.js" type="text/javascript"></script>
-->
    <link href="favicon.ico" rel="icon" type="image/x-icon">
    <link href=
    "http://fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic|Shadows+Into+Light"
    rel="stylesheet" type="text/css">
    <script data-main="/js/lena_clare/main" src="/js/lena_clare/lib/require.js"></script>
</head>

<body>
    <div class="wrapper">
        <!-- Header -->

        <div class="header">
            <!-- Top bar -->

            <div class="top">
                <div class="container">
                    <div class="row">
                        <div class="span6">
                            <!--<p>Responsive eCommerce template &mdash; <a href=
                            "http://themeforest.net/item/la-boutique-responsive-ecommerce-template/5573130?ref=Tfingi">
                            <strong>BUY NOW!</strong></a></p>-->
                        </div>

                        <div class="span6 hidden-phone">
                            <ul class="inline pull-right">
                                <li>
                                    <a href="login-register.html" title=
                                    "Login / Register">Login / Register</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div><!-- End class="top" -->
            <!-- Logo & Search bar -->

            <div class="bottom">
                <div class="container">
                    <div class="row">
                        <div class="span8">
                            <div class="logo">
                                <a href="index.html" title=
                                "&larr; Back home"><img alt="La Boutique" src=
                                "img/LC-Name-Logo_Medium.jpg"></a>
                            </div>
                        </div>

                        <div class="span4">
                            <div class="row-fluid">
                                <div class="span10">
                                    <!-- Search -->

                                    <div class="search">
                                        <div class="qs_s">
                                            <form action="search.html" method=
                                            "post">
                                                <input autocomplete="off" id=
                                                "query" name="query"
                                                placeholder="Search&hellip;"
                                                type="text" value="">
                                            </form>
                                            <!-- Autocomplete results -->

                                            <div id="autocomplete-results"
                                            style="display: none;">
                                                <ul>
                                                    <li>
                                                        <a href="product.html"
                                                        title="Lisette Dress">
                                                        <div class="image">
                                                        <img alt="" src=
                                                        "img/thumbnails/db_file_img_48_60x60.jpg"></div>

                                                        <h6>Lisette
                                                        Dress</h6></a>
                                                    </li>

                                                    <li>
                                                        <a href="product.html"
                                                        title="Malta Dress">
                                                        <div class="image">
                                                        <img alt="" src=
                                                        "img/thumbnails/db_file_img_137_60x60.jpg"></div>

                                                        <h6>Malta
                                                        Dress</h6></a>
                                                    </li>

                                                    <li>
                                                        <a href="product.html"
                                                        title="Marais Dress">
                                                        <div class="image">
                                                        <img alt="" src=
                                                        "img/thumbnails/db_file_img_42_60x60.jpg"></div>

                                                        <h6>Marais
                                                        Dress</h6></a>
                                                    </li>

                                                    <li>
                                                        <a href="product.html"
                                                        title="Millay Dress">
                                                        <div class="image">
                                                        <img alt="" src=
                                                        "img/thumbnails/db_file_img_107_60x60.jpg"></div>

                                                        <h6>Millay
                                                        Dress</h6></a>
                                                    </li>

                                                    <li>
                                                        <a href="product.html"
                                                        title="Momoko Dress">
                                                        <div class="image">
                                                        <img alt="" src=
                                                        "img/thumbnails/db_file_img_132_60x60.jpg"></div>

                                                        <h6>Momoko
                                                        Dress</h6></a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <!-- End id="autocomplete-results" -->
                                        </div>
                                    </div><!-- End class="search"-->
                                </div>

                                <div class="span2">
                                    <!-- Mini cart -->

                                    <div class="mini-cart">
                                        <a href="cart.html" title=
                                        "Go to cart &rarr;"><span>3</span></a>
                                    </div><!-- End class="mini-cart" -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- End class="bottom" -->
        </div><!-- End class="header" -->
        <?php echo $this->partial('partials/nav_menu.phtml'); ?>
        <!-- Content section -->

        <section class="main">
            <!-- Home content -->

            <section class="home">
                <!-- Slider -->

                <section class="flexslider">
                    <ul class="slides">
                        <li>
                            <img alt="" src="img/slides/1.jpg">

                            <div class="caption">
                                <div class="container">
                                    <div class="span6">
                                        <h3>360+ Retina-ready icons</h3><br>

                                        <p>The iconic Font Awesome for
                                        Bootstrap</p><br>
                                        <a class="btn btn-small" href=
                                        "/retina-ready-icons" title="">Find out
                                        more</a> <a class=
                                        "btn btn-primary btn-small" href="#"
                                        title="">Buy now &nbsp; <em class=
                                        "icon-chevron-right"></em></a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img alt="" src="img/slides/2.jpg">

                            <div class="caption">
                                <div class="container">
                                    <div class="span6">
                                        <h3>Built-in Stripe payments</h3><br>

                                        <p>Instant setup with payment profiles.
                                        No monthly fees.</p><br>
                                        <a class="btn btn-small" href="#"
                                        title="">Find out more</a> <a class=
                                        "btn btn-primary btn-small" href="#"
                                        title="">Buy now &nbsp; <em class=
                                        "icon-chevron-right"></em></a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img alt="" src="img/slides/3.jpg">

                            <div class="caption">
                                <div class="container">
                                    <div class="span6 offset6 text-right">
                                        <h3>Feature-packed modules</h3><br>

                                        <p>Isotope listing, price filtering,
                                        instand search and much more...</p><br>
                                        <a class="btn btn-small" href="#"
                                        title="">Find out more</a> <a class=
                                        "btn btn-primary btn-small" href="#"
                                        title="">Buy now &nbsp; <em class=
                                        "icon-chevron-right"></em></a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <li>
                            <img alt="" src="img/slides/4.jpg">

                            <div class="caption">
                                <div class="container">
                                    <div class="span6 offset6 text-right">
                                        <h3>Responsive. Flexible &amp;
                                        sleek.</h3><br>

                                        <p>Expertly crafted with Bootstrap
                                        front-end framework</p><br>
                                        <a class="btn btn-small" href="#"
                                        title="">Find out more</a> <a class=
                                        "btn btn-primary btn-small" href="#"
                                        title="">Buy now &nbsp; <em class=
                                        "icon-chevron-right"></em></a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </section><!-- End class="flexslider" -->

                <section class="featured">
                    <div class="container">
                        <div class="row">
                            <div class="span9">
                                <!-- Products list -->

                                <ul class="product-list isotope">
                                    <li class="standard" data-price="27">
                                        <a href="/" title=
                                        "Small Convertible Purse Blue and Yellow">
                                        <div class="image"><img alt=
                                        "Small Convertible Purse Blue and Yellow" class="primary" src=
                                        "img/products/purses/blue_and_yellow_plaid_gallery_1.jpg">
                                        <img alt="Small Convertible Purse Blue and Yellow" class=
                                        "secondary" src=
                                        "img/products/purses/blue_and_yellow_plaid_gallery_3.jpg"></div>

                                        <div class="title">
                                            <div class="prices">
                                                <span class=
                                                "price">$27.00</span>
                                            </div>

                                            <h3>Small Convertible Purse Blue and Yellow</h3>
                                        </div></a>
                                    </li>
                                    <li class="standard" data-price="7">
                                        <a href="/" title=
                                        "Wine Bag Cream and Brown Love Birds">
                                        <div class="image"><img alt=
                                        "Wine Bag Cream and Brown Love Birds" class="primary" src=
                                        "img/products/handbags/cream_and_brown_toile_lovebirds_gallery_1.jpg">
                                        <img alt="Wine Bag Cream and Brown Love Birds" class=
                                        "secondary" src=
                                        "img/products/handbags/cream_and_brown_toile_lovebirds_gallery_3.jpg"></div>

                                        <div class="title">
                                            <div class="prices">
                                                <span class=
                                                "price">$7.00</span>
                                            </div>

                                            <h3>Wine Bag Cream and Brown Love Birds</h3>
                                        </div></a>
                                    </li>
                                    <li class="standard" data-price="7">
                                        <a href="/" title=
                                        "Wine Bag Charcoal and Cream Tulip">
                                        <div class="image"><img alt=
                                        "Wine Bag Charcoal and Cream Tulip" class="primary" src=
                                        "img/products/handbags/charcoal_and_cream_tulip_gallery_1.jpg">
                                            <span class=
                                            "badge badge-sale">SALE</span>
                                        <img alt="Wine Bag Charcoal and Cream Tulip" class=
                                        "secondary" src=
                                        "img/products/handbags/charcoal_and_cream_tulip_gallery_3.jpg"></div>

                                        <div class="title">
                                            <div class="prices">
                                                <span class=
                                                "price">$7.00</span>
                                            </div>

                                            <h3>Wine Bag Charcoal and Cream Tulip</h3>
                                        </div></a>
                                    </li>
                                    <li class="standard" data-price="7">
                                        <a href="/" title=
                                        "Wine Bag Cream and Brown Toile">
                                        <div class="image"><img alt=
                                        "Wine Bag Cream and Brown Toile" class="primary" src=
                                        "img/products/handbags/cream_and_brown_toile_gallery_1.jpg">
                                        <img alt="Wine Bag Cream and Brown Toile" class=
                                        "secondary" src=
                                        "img/products/handbags/cream_and_brown_toile_gallery_3.jpg"></div>

                                        <div class="title">
                                            <div class="prices">
                                                <span class=
                                                "price">$7.00</span>
                                            </div>

                                            <h3>Wine Bag Cream and Brown Toile</h3>
                                        </div></a>
                                    </li>
                                    <li class="standard" data-price="7">
                                        <a href="/" title=
                                        "Wine Bag Red and Brown Toile">
                                        <div class="image"><img alt=
                                        "Wine Bag Red and Brown Toile" class="primary" src=
                                        "img/products/handbags/red_and_brown_toile_gallery_1.jpg">
                                        <img alt="Wine Bag Red and Brown Toile" class=
                                        "secondary" src=
                                        "img/products/handbags/red_and_brown_toile_gallery_3.jpg"></div>

                                        <div class="title">
                                            <div class="prices">
                                                <span class=
                                                "price">$7.00</span>
                                            </div>

                                            <h3>Wine Bag Red and Brown Toile</h3>
                                        </div></a>
                                    </li>
                                    <li class="standard" data-price="7">
                                        <a href="/" title=
                                        "Wine Bag Green and Cream Toile Pheasant">
                                        <div class="image"><img alt=
                                        "Wine Bag Green and Cream Toile Pheasant" class="primary" src=
                                        "img/products/handbags/green_and_cream_toile_pheasant_gallery_1.jpg">
                                        <img alt="Wine Bag Green and Cream Toile Pheasant" class=
                                        "secondary" src=
                                        "img/products/handbags/green_and_cream_toile_pheasant_gallery_3.jpg"></div>

                                        <div class="title">
                                            <div class="prices">
                                                <span class=
                                                "price">$7.00</span>
                                            </div>

                                            <h3>Wine Bag Green and Cream Toile Pheasant</h3>
                                        </div></a>
                                    </li>
                                </ul><!-- End class="product-list isotope" -->
                            </div>

                            <div class="span3">
                                <!-- Categories widget -->

                                <div class="widget Categories">
                                    <h3 class="widget-title widget-title">
                                    Categories</h3>

                                    <ul>
                                        <li>
                                            <a class="title" href=
                                            '/'>Bags</a>
                                            <ul>
                                                <li>
                                                    <a class="title" href=
                                                    '/'>Purses</a>
                                                </li>

                                                <li>
                                                    <a class="title" href=
                                                    '/'>Wine Bags</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div><!-- End class="widget Categories" -->
                                <!-- This month only! widget -->

                                <!--<div class="widget Text">
                                    <h3 class="widget-title widget-title">This
                                    month only!</h3>

                                    <h5>Free UK shipping!</h5>

                                    <h6><i class="icon-gift">&nbsp;</i> Free
                                    gift wrap</h6>

                                    <p>Lorem ipsum dolor sit amet, consectetur
                                    adipisicing elit. Neque beatae tempore
                                    porro officiis!</p><a class=
                                    "btn btn-primary" href="#">BUY NOW
                                    <em>for</em> $85</a>
                                </div>--><!-- End class="widget Text" -->
                            </div>
                        </div>
                    </div>
                </section>
            </section><!-- End class="home" -->
        </section><!-- End class="main" -->
        <!-- Twitter bar -->

        <!--<div class="twitter-bar">
            <div class="container">
                <div class="row">
                    <div class="span12">
                        <div class="icon icon-twitter" style=
                        "font-style: italic"></div>

                        <div data-username="lemonstand" id="tweets"></div>
                    </div>
                </div>
            </div>
        </div>--><!-- End class="twitter-bar" --><!-- Footer -->

        <div class="footer">
            <div class="container">
                <div class="row">
                    <!--<div class="span2">-->
                        <!-- Support -->

                        <!--<div class="support">
                            <h6>Support</h6>

                            <ul class="links">
                                <li>
                                    <a class="title" href="about-us.html"
                                    title="About us">About us</a>
                                </li>

                                <li>
                                    <a class="title" href="typography.html"
                                    title="Typography">Typography</a>
                                </li>

                                <li>
                                    <a class="title" href=
                                    "retina-ready-icons.html" title=
                                    "Retina-ready icons">Retina-ready icons</a>
                                </li>

                                <li>
                                    <a class="title" href="buttons.html" title=
                                    "Buttons">Buttons</a>
                                </li>

                                <li>
                                    <a class="title" href="elements.html"
                                    title="Elements">Elements</a>
                                </li>

                                <li>
                                    <a class="title" href="grids.html" title=
                                    "Grids">Grids</a>
                                </li>

                                <li>
                                    <a class="title" href="store-locator.html"
                                    title="Store locator">Store locator</a>
                                </li>

                                <li>
                                    <a class="title" href="contact-us.html"
                                    title="Contact us">Contact us</a>
                                </li>
                            </ul>
                        </div>--><!-- End class="support" -->
                        <!--<hr>-->
                        <!-- My account -->

                        <!--<div class="account">
                            <h6>My account</h6>

                            <ul class="links">
                                <li>
                                    <a href="login-register.html" title=
                                    "Login / Register">Login / Register</a>
                                </li>
                            </ul>
                        </div>--><!-- End class="account"-->
                    <!--</div>-->

                    <div class="span2">
                        <!-- Categories -->

                        <div class="categories">
                            <h6>Shop</h6>

                            <ul class="links">
                                <li>
                                    <a href="javascript:void(0)" title=
                                    "Purses">Purses</a>
                                </li>

                                <li>
                                    <a href="javascript:void(0)" title="Wine Bags">Wine Bags</a>
                                </li>
                            </ul>
                        </div><!-- End class="categories" -->
                        <hr>
                        <!-- Pay with confidence -->

                        <div class="confidence">
                        <h6>Pay with confidence</h6><img alt=
                        "We accept all major credit cards" src=
                        "img/stripe.png"></div><!-- End class="confidence" -->
                    </div>

                    <div class="span4">
                        <h6>From the blog</h6>

                        <ul class="list-chevron links">
                            <li>
                                <a href="blog-post.html">Article with video</a>
                                <small>05/01/2013</small>
                            </li>

                            <li>
                                <a href="blog-post.html">Article with
                                images</a> <small>03/14/2013</small>
                            </li>

                            <li>
                                <a href="blog-post.html">Article with
                                style!</a> <small>08/31/2013</small>
                            </li>
                        </ul>
                    </div>

                    <div class="span4">
                        <!-- Newsletter subscription -->

                        <div class="newsletter">
                            <h6>Join our mailing list</h6>

                            <form action="index.html" enctype=
                            "multipart/form-data" method="post" onsubmit=
                            "$('#newsletter_subscribe').modal('show'); return false;">
                            <div class="input-append">
                                    <input class="span3" name="email" type=
                                    "text"> <button class="btn" type=
                                    "submit">Join!</button>
                                </div>
                            </form>

                            <p>Sign up to receive our latest news and updates
                            direct to your inbox</p>
                        </div><!-- End class="newsletter" -->
                        <hr>
                        <!-- Social icons -->

                        <div class="social">
                            <h6>Socialize with us</h6>

                            <ul class="social-icons">
                                <li>
                                    <a class="twitter" href="#" title=
                                    "Twitter">Twitter</a>
                                </li>

                                <li>
                                    <a class="facebook" href="#" title=
                                    "Facebook">Facebook</a>
                                </li>

                                <li>
                                    <a class="pinterest" href="#" title=
                                    "Pinterest">Pinterest</a>
                                </li>

                                <li>
                                    <a class="tumblr" href="#" title=
                                    "Tumblr">Tumblr</a>
                                </li>

                                <li>
                                    <a class="linkedin" href="#" title=
                                    "LinkedIn">LinkedIn</a>
                                </li>

                                <li>
                                    <a class="instagram" href="#" title=
                                    "Instagram">Instagram</a>
                                </li>
                            </ul>
                        </div><!-- End class="social" -->
                    </div>
                </div>
            </div>
        </div><!-- End id="footer" -->
        <!-- Credits bar -->

        <div class="credits">
            <div class="container">
                <div class="row">
                    <div class="span8">
                        <p>&copy; 2014 LenaClare &middot; All
                        Rights Reserved.</p>
                    </div>

                    <div class="span4 text-right hidden-phone">
                        <p><a href=
                        "http://themeforest.net/item/la-boutique-responsive-ecommerce-template/5573130?ref=Tfingi"
                        title="Responsive eCommerce template">Responsive
                        eCommerce template by Tfingi</a></p>
                    </div>
                </div>
            </div>
        </div><!-- End class="credits" --><!-- Newsletter modal window -->

        <div class="modal hide fade" id="newsletter_subscribe" tabindex="-1">
            <div class="modal-header">
                <button class="close" data-dismiss="modal" type=
                "button">√ó</button>

                <div class="hgroup title">
                    <h3>You are now subscribed to our newsletter</h3>

                    <h5>All the latest deals and offers will be making their
                    way to your inbox shortly!</h5>
                </div>
            </div>

            <div class="modal-footer">
                <div class="pull-left">
                    <button class="btn btn-small" data-dismiss="modal">Close
                    &nbsp; <i class="icon-ok"></i></button>
                </div>
            </div>
        </div><!-- End id="newsletter_subscribe" -->
    </div><!-- BEGIN JAVASCRIPTS -->
    <!--<script src=
    "http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type=
    "text/javascript"></script>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false"
type="text/javascript"></script> 
    <script src="js/jquery-ui-1.10.2.custom.js" type="text/javascript"></script>
    <script src="js/jquery.easing-1.3.min.js" type="text/javascript"></script>
    <script src="js/bootstrap.js" type="text/javascript"></script>
    <script src="js/jquery.isotope.min.js" type="text/javascript"></script>
    <script src="js/jquery.flexslider.js" type="text/javascript"></script>
    <script src="js/jquery.elevatezoom.js" type="text/javascript"></script>
    <script src="js/jquery.sharrre-1.3.4.js" type="text/javascript"></script>
    <script src="js/jquery.gmap3.js" type="text/javascript"></script>
    <script src="js/jquery.tweet.js" type="text/javascript"></script>
    <script src="js/imagesloaded.js" type="text/javascript"></script>
    <script src="js/la_boutique.js" type="text/javascript"></script>
    <script src="js/megamenu_plugins.js" type="text/javascript"></script>
    <script src="js/megamenu.js" type="text/javascript"></script>
    <script src="js/jquery.cookie.js" type="text/javascript"></script>-->
</body>
</html>