<nav class="navigation">
    <div class="container">
        <div class="row">
            <div class="span9">
                <div class="megamenu_container  megamenu_light"><!-- Begin Menu Container -->


                    <ul class="megamenu"><!-- Begin Mega Menu -->

                        <li class="megamenu_button"><a href="#_">Go to...<i class="icon  icon-chevron-down"></i></a></li>


                        <li>
                            <a href="#_" class="megamenu_drop">Home</a>
                        </li><!-- End Item -->

                        <li>
                            <a href="#_" class="megamenu_drop">Shop</a><!-- Begin Item -->


                            <div class="dropdown_2columns dropdown_container"><!-- Begin Item Container -->

                                <ul class="dropdown_flyout">
                                    <li class="dropdown_parent"><a href="http://www.twindots.com">Bags</a>

                                        <ul class="dropdown_flyout_level">
                                            <li>
                                                <a href="javascript:void(0)" title="Purses">Purses</a>
                                            </li>
                                            <li>
                                                <a href="javascript:void(0)" title="Wine Bags">Wine Bags</a>
                                            </li>
                                        </ul>

                                    </li>

                                </ul>                   
                            </div><!-- End Item Container -->
                        </li><!-- End Item -->


                        <li><a href="#_" class="megamenu_drop">Account</a><!-- Begin Item -->


                            <div class="dropdown_6columns dropdown_container"><!-- Begin Item Container -->


                                <div class="col_5 responsive_halfs">
                                <h3>New</h3>
                                        <ul class="list_unstyled">
                                            <li>
                                                <a href="javascript:void(0)" title="Register" class="title">Register</a>
                                            </li>
                                    </ul>   

                                </div>

                                <div class="col_5 responsive_halfs">
                                <h3>Existing</h3>

                                    <ul class="list_unstyled">
                                        <li>
                                            <a href="javascript:void(0)" title="Login" class="title">Login</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" title="Order History" class="title">Order History</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" title="Reset Password" class="title">Reset Password</a>
                                        </li>
                                        <li>
                                            <a href="javascript:void(0)" title="Checkout" class="title">Checkout</a>
                                        </li>
                                    </ul>   
                                </div>


                                <div class="col_12">
                                    <hr>
                                    <h3>Socialize with us</h3>              
                                    <div class="social">

                                        <ul class="social-icons">

                                            <li>
                                                <a title="Twitter" href="#" class="twitter">Twitter</a>								
                                            </li>

                                            <li>
                                                <a title="Facebook" href="#" class="facebook">Facebook</a>								
                                            </li>

                                            <li>
                                                <a title="Pinterest" href="#" class="pinterest">Pinterest</a>								
                                            </li>

                                            <li>
                                                <a title="Tumblr" href="#" class="tumblr">Tumblr</a>								
                                            </li>

                                            <li>
                                                <a title="LinkedIn" href="#" class="linkedin">LinkedIn</a>								
                                            </li>

                                            <li>
                                                <a title="Instagram" href="#" class="instagram">Instagram</a>								
                                            </li>

                                        </ul>
                                    </div>
                                </div>


                            </div><!-- End Item container -->


                        </li><!-- End Item -->


                        <li><a href="#_" class="megamenu_drop">Contact Us</a><!-- Begin Item -->


                            <div class="dropdown_5columns dropdown_container"><!-- Begin Item Container -->


                                <div class="col_12">

                                    <h3>Get in touch!</h3>
                                    <!--<p>A nicely styled contact form straight from your mega menu.</p>-->

                                    <div class="contact_form">

                                        <form action="send">

                                            <label for="name">Name<span class="required"> *</span></label>
                                            <input name="name" type="text" class="form_element" id="name" value="" autocomplete="off" /> 

                                            <label for="email">Email<span class="required"> *</span></label>
                                            <input name="email" type="text" class="form_element" id="email" value="" autocomplete="off" />

                                            <label for="message">Message<span class="required"> *</span></label>
                                            <textarea name="message" class="form_element" id="message"></textarea>

                                            <div class="form_buttons">
                                                <input type="submit" class="button btn-primary" id="submit" value="Submit" />
                                                <input type="reset" class="button" id="reset" value="Reset" />
                                            </div>

                                        </form>

                                    </div>

                                </div>


                            </div><!-- End Item Container -->


                        </li><!-- End Item -->


                        <li>
                            <a href="javascript:void(0)" title="Events" class="title">Events</a>
                        </li>
                        <li>
                            <a href="javascript:void(0)" title="Blog" class="title">Blog</a>
                        </li>
                    </ul><!-- End Mega Menu -->


                </div><!-- End Menu Container -->
            </div>

            <div class="span3 visible-desktop"></div>
        </div>
    </div>
</nav>